### ISSUE TITLE
[btnext] Login failed: No form found on http://tracker.btnext.com/?p=home

### ISSUE THREAD

**Issue by fleyd-1** [Jackett/Jackett#12535]
### Have you checked our Troubleshooting page for your issue?

- [ ] I have checked the Troubleshooting page

### Is there already an issue for your problem?

- [ ] I have checked older issues, open and closed

### Have you read our Contributing Guidelines?

- [ ] I have read the Contributing Guidelines

### Environment

```markdown
2021-11-10 14:41:45	Info	Loading Native indexers ...
2021-11-10 14:41:45	Info	Using HTTP Client: HttpWebClient2
2021-11-10 14:41:45	Info	Using FlareSolverr: No
2021-11-10 14:41:45	Info	Using proxy: Disabled
2021-11-10 14:41:45	Info	App config/log directory: /config/Jackett
2021-11-10 14:41:45	Info	ThreadPool MaxThreads: 32767 workerThreads, 1000 completionPortThreads
2021-11-10 14:41:45	Info	Running in Docker: Yes (image build: v0.17.794-ls25)
2021-11-10 14:41:45	Info	File /etc/issue: Ubuntu 18.04.5 LTS \n \l
2021-11-10 14:41:45	Info	Jackett variant: CoreLinuxAmdx64
2021-11-10 14:41:45	Info	OS version: Unix 4.4.180.0 (64bit OS) (64bit process)
2021-11-10 14:41:45	Info	Environment version: 5.0.12 (/app/Jackett/)
2021-11-10 14:41:42	Info	Starting Jackett v0.19.215
```

### Description

I´m unable to add a Portuguese private tracker name BtNext.

Could the problem be that Jackett indexes http and the real URL is  https ://tracker.btnext. com/  ?

Not sure, just trying to help finding a solution.

Any ideas?

Thanks.

### Logged Error Messages

An error occurred while updating this indexer
Login failed: No form found on http ://tracker.btnext. com/?p=home&pid=1 using form selector form#loginbox_form
Click here to open an issue on 
![Captura de ecrã 2021-11-10 143916](https://user-images.githubusercontent.com/64219933/141133324-61e40f73-0c71-435a-823b-dbbbb383d667.png)
GitHub for this indexer.

### Screenshots

![image](https://user-images.githubusercontent.com/64219933/141132728-e7addaf6-4304-47b1-97a7-a95d1856f1cb.png)

**Comment by ilike2burnthing** [comment]
Change the sitelink to https or wait for the next release in ~14hrs

**Comment by garfield69** [comment]
@fleyd-1  No, the log you just provided is the _regular_ one, and we asked you to provide an **enhanced** log, which has additional debug and HTML included.
Without this we cannot get any clues to your issues. 
Remember any time you restart Jackett the enhanced log switch is turned off, so turn the switch on, click the apply-server-settings, and test using **ONLY** btnext (to avoid cluttering the log with all the other indexer traffic), and capture the log for that indexer and post it here.
Thanks.

**Comment by garfield69** [comment]
v0.19.228

**Comment by fleyd-1** [comment]
[log jackett.txt](https://github.com/Jackett/Jackett/files/7523643/log.jackett.txt)

Hi and sorry for the delay. I think the attached is the enhanced log right?

It seems to be working fine now. Thanks for the help.
