### ISSUE TITLE
French Private Tracker's ROADMAP

### ISSUE THREAD

**Issue by JigSawFr** [Jackett/Jackett#145]
##### Hello everyone, (and especially french users of Jackett)

In process of adding more providers to Jackett,
I will build many providers for french private trackers,
So you can see here what is on progress and what is done.
Feel free to suggest trackers

**Roadmap**
- [x] WiHD (PR https://github.com/Jackett/Jackett/pull/137 https://github.com/Jackett/Jackett/pull/150 ~ Merged)
- [x] Abnormal (PR https://github.com/Jackett/Jackett/pull/174 - Merged)
- [x] Xthor (ISS. https://github.com/Jackett/Jackett/issues/289 - PR #295 - Merged)
- [x] Fix Dev Mod for Cross Plateform OS
- [x] Check Xthor
- [x] Check Abnormal
- [ ] Check WiHD
- ~~HD-Only~~ (_Waiting for improvements on tracker side_)
- ~~BlueTigers~~ (_Rewrite_)
- [x] ~~PhxBit (PR #290 #293 - Merged)~~ **Tracker Closed**
- [x] ~~French-ADN (PR https://github.com/Jackett/Jackett/pull/153 #299 ~ Merged)~~ **Tracker Closed**
- [x] ~~FNT (ISS. https://github.com/Jackett/Jackett/issues/14 - PR https://github.com/Jackett/Jackett/pull/149 https://github.com/Jackett/Jackett/issues/156 ~ Merged)~~ **Tracker Closed**

**Main Features**
- Search on Tracker (_Categories supported for querying among all categories_)
- Advanced Search Parameters (_Such as Freeleech, Dead, 3D, Reseed, ..._)
- Max Page Crawling for results (_default to 4_)
- Browser Simulation (_Injecting additionals headers to request, configurable_)
- Latency Simulation (_Between a range of two milliseconds numbers, configurable_)
- Advanced Configuration with messages displayed
- Settings checked and validated before saving.
- Calculated date from "Ago date" (_Function needed for some trackers_)
- Dev mode for developers (_output to logfile in prod, console in dev_)
- Cache on hard drive mode for developers with automated configurable cleaning (_reduce http requests when testing and building parser_) 

**Issues**
If you have issues with providers, **please create a new issue !** Thanks you.

Happy New Year :fireworks:

**Comment by raspdealer** [comment]
oh yeah.

**Comment by maxcore** [comment]
:) !!!

**Comment by JigSawFr** [comment]
WiHD merged, enjoy !

**Comment by maxcore** [comment]
@JigSawFr  great job !

**Comment by JigSawFr** [comment]
I'm rebasing FNT before PR.
And i will create an HOT fix for latest version (bugs found for ressources, images not displayed)

**Comment by maxcore** [comment]
great this one i can test hehe

**Comment by JigSawFr** [comment]
Improved WiHD Provider, PR submited.

**Comment by JigSawFr** [comment]
Started French-ADN.

**Comment by JigSawFr** [comment]
WiHD improvement PR merged and FNT Provider available ! enjoy :lollipop:

**Comment by raspdealer** [comment]
Thanks!

**Comment by JigSawFr** [comment]
French-ADN done .... Pending Approval :)

**Comment by eyotiste** [comment]
Thx @JigSawFr

**Comment by maxcore** [comment]
@JigSawFr cant wait to test ;)

**Comment by Bybou** [comment]
Je viens de tester concernant FnT et j'ai "presque" réussi, j'obtiens une erreur lors du téléchargement du torrent :
Message : Downloading torrent file for episode 'Marvels.Daredevil.S01E01.VOSTFR.720p.WEBRip.x264.AC3-MuskeTeerS' failed (http://localhost:9117/dl/fnt/scpy57ihbfaico3rt51j2stuttwa?path=aHR0cDovL2ZudC5udS9kb3dubG9hZC5waHA_aWQ9OTc0OTkmZGw9b3Vp0&file=Marvels.Daredevil.S01E01.VOSTFR.720p.WEBRip.x264.AC3-MuskeTeerS.torrent): HTTP request failed: [404:NotFound] [GET] at [http://localhost:9117/dl/fnt/scpy57ihbfaico3rt51j2stuttwa?path=aHR0cDovL2ZudC5udS9kb3dubG9hZC5waHA_aWQ9OTc0OTkmZGw9b3Vp0&file=Marvels.Daredevil.S01E01.VOSTFR.720p.WEBRip.x264.AC3-MuskeTeerS.torrent]

Exception : NzbDrone.Common.Http.HttpException: HTTP request failed: [404:NotFound] [GET] at [http://localhost:9117/dl/fnt/scpy57ihbfaico3rt51j2stuttwa***?path=aHR0cDovL2ZudC5udS9kb3dubG9hZC5waHA_aWQ9OTc0OTkmZGw9b3Vp0&file=Marvels.Daredevil.S01E01.VOSTFR.720p.WEBRip.x264.AC3-MuskeTeerS.torrent]
at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00184] in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\HttpClient.cs:105 
at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Common\Http\HttpClient.cs:188 
at NzbDrone.Core.Download.TorrentClientBase`1[NzbDrone.Core.Download.Clients.RTorrent.RTorrentSettings].DownloadFromWebUrl (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode, System.String torrentUrl) [0x00021] in m:\BuildAgent\work\6c3239faf2b92630\src\NzbDrone.Core\Download\TorrentClientBase.cs:106

On dirait un problème lors de la construction de l'url pour récupérer le .torrent non ?
Peut-être que j'ai mal configuré quelque chose dans Jackett concernant FnT ? Je ne rencontre pas ce genre de problème sur les autres trackers que j'ai paramétré.

En tout cas c'est génial.
Merci :)

**Comment by JigSawFr** [comment]
@Bybou Please create a new issue if you want me to resolve your problem ;) 

French: merci de créer une nouvelle issue afin que votre problème soit traité.

**Comment by JigSawFr** [comment]
Started ABN.

> ETA:

- [ ] Creating new provider (initial step)
- [ ] Logo
- [ ] Categories mapping
- [ ] Provider advanced settings
- [ ] Login
- [ ] Search Query
- [ ] Parsing rows
- [ ] Search Query with categories
- [ ] Search Query with parameters
- [ ] Pagination Support
- [ ] Tests done

> Informations on release:

- [ ] ID
- [ ] Title
- [ ] Guid
- [ ] Description Link
- [ ] Download Link
- [ ] MinimumSeedTime
- [ ] MinimumRatio
- [ ] Category (+ name)
- [ ] Files
- [ ] Health
- [ ] Genre
- [ ] Date
- [ ] Size
- [ ] Description
- [ ] Seeders
- [ ] Leechers
- [ ] Peers
- [ ] Comments
- [ ] Comments Link
- [ ] Uploader

> Striked informations mean they are not available on tracker side in torrent search page.

**Comment by fana13** [comment]
You're really crazy @JigSawFr !!
Thanks a lot for your work.
Do you think it's possible to add Ethor to your  french roadmap ?
PTP it's not in your US plan ?

**Comment by raspdealer** [comment]
Im definitively waiting for PhxBit and bluetigers!!!!

**Comment by maxcore** [comment]
@JigSawFr  amazing work :)

**Comment by eyotiste** [comment]
@raspdealer Can you send some info about this tracker by mp ? (PhxBit)

**Comment by raspdealer** [comment]
Sent

**Comment by raspdealer** [comment]
Should youadd ethor at the end of this roadmap?
Bluetigers migration is done... but jackett doesnt like it.
Can you have a look too?
Thanks!

**Comment by itdaboyz** [comment]
About PhxBit, what will be the next step ? I see "Login problem on tracker by Jackett Core". Is this planned to be fixed in the near future ?
Thanks

**Comment by JigSawFr** [comment]
@itdaboyz connection is immediately closed after a simple request (GET) of index page. Don't know why (maybe @Azerelat or @flightlevel have an idea on this error).

The underlying connection was closed: The connection was closed unexpectedly.

I suspect Jackett to send Extra headers not supported by tracker's server/website.
For example "Expect:100-continue". Need to see if it's not .Net framework bug, or if it its resolved on upper version.

**Comment by raspdealer** [comment]
Suggestions: 
- https://github.com/Jackett/Jackett/issues/200
- https://github.com/Jackett/Jackett/issues/182
- https://github.com/Jackett/Jackett/issues/166

**Comment by itdaboyz** [comment]
@JigSawFr Any progress on this error ? I asked the staff on PhxBit and they have no clue about what could prevent Jackett from connecting to their site.
Thank you

**Comment by JigSawFr** [comment]
I think it's a problem on Jackett core, i'm very busy at this time at work. So i will investigate in next week how to do it. If no clues are found, i will wait next jackett version to build it.

**Comment by bioshock47** [comment]
Hello,

I try to look in the discussion but i can't find anything about t411. Is it possible to have it in jackett?
Thanks

**Comment by raspdealer** [comment]
anything about t411? really?

**Comment by bioshock47** [comment]
I try ctrl + f with and i don't see it. Sorry i'm now with git so i have dificultis with it, but i just want to learn^^

**Comment by raspdealer** [comment]
https://github.com/Jackett/Jackett/issues?utf8=%E2%9C%93&q=is%3Aissue+t411

**Comment by bioshock47** [comment]
........................ ok ok i don't say anything ^^
sorry for the missunderstanding

**Comment by itdaboyz** [comment]
Ok @JigSawFr thanks for looking at this and sorry if my message sounded impatient.

**Comment by itdaboyz** [comment]
@JigSawFr It seems that PhxBit's admin made some changes and he ask if you can try again to connect.

**Comment by Barracuda26** [comment]
Yes go retest login please :)

**Comment by JigSawFr** [comment]
PhxBit is now under my roadmap again. I'm now logged in with Jackett.
Provider will be available soon !

![PHX](https://i.imgur.com/lTP59YF.png)

**Comment by maxcore** [comment]
@JigSawFr welcome back jig ;)

**Comment by JigSawFr** [comment]
Started PHX.

> ETA:

- [x] Creating new provider (initial step)
- [x] Logo
- [x] Categories mapping
- [x] Provider advanced settings
- [x] Login
- [x] Search Query
- [x] Parsing rows
- [x] Search Query with categories
- [x] Search Query with parameters
- [x] Pagination Support
- [x] Tests done

> Informations on release:

- [x] ID
- [x] Title
- [x] Guid
- [x] Description Link
- [x] Download Link
- [x] MinimumSeedTime
- [x] MinimumRatio
- [x] Category (+ name)
- ~~Files~~
- ~~Health~~
- [x] Genre
- [x] Date
- [x] Size
- [x] Description
- [x] Seeders
- [x] Leechers
- [x] Peers
- [x] Comments
- [x] Comments Link
- [x] Uploader

> Striked informations mean they are not available on tracker side in torrent search page.

**Comment by JigSawFr** [comment]
PhxBit done :)

**Comment by maxcore** [comment]
can't wait to try it :)

**Comment by dardano** [comment]
Hi, any ETA for #182 ?
Thanks

**Comment by JigSawFr** [comment]
@maxcore you will enjoy it ;)

@dardano Ethor is protected by a captcha, need to implement a captcha solver or use a captcha solver service, but i will try with just an existing logged cookie. I can't promise anything for this tracker, sorry.

**Comment by fana13** [comment]
Thanks JigSaw, great job :)

**Comment by Bybou** [comment]
Thanks a lot !

Le mercredi 30 mars 2016, fana13 <notifications@github.com> a écrit :

> Thanks JigSaw, great job :)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Jackett/Jackett/issues/145#issuecomment-203249792>
>


-- 

Cordialement,


*Johan Copin*

johan.copin@gmail.com <jcopin@micropole.com>

**Comment by JigSawFr** [comment]
**Started with Xthor.**
_Thanks to @cocolabombe0_
As it's now using an API, it will require more rewrite to do it properly.
Coming soon.

**Comment by JigSawFr** [comment]
Almost finished for Xthor, need some tests and categories mapping :)

**Comment by maxcore** [comment]
@JigSawFr PhxBit work perfect !!


i have try search with French-adn and no return releases . with couch and with main search in jackett , all other jackett found the releases : 
i have test with ' A Walk in the Woods '

**Comment by JigSawFr** [comment]
@maxcore i will investigate soon, can you open a new issue with logs and important informations about your problem. Great to know that Phxbit work perfectly :)

Xthor is working too, i'm cleaning code and develop analyze of error code, i will release it as soon as possible ;)

**Comment by Nonobis** [comment]
could you add http://www.qctorrent.io to your list ?
thanks :)

**Comment by JigSawFr** [comment]
@Nonobis Sorry QcTorrent is a public tracker, only private trackers are allowed in Jacket at this state.

**Comment by eyotiste** [comment]
A little issue in the mapping categorie of PhxBit, the "Manga" categorie is for Japanime, and the Anime for "children (disney etc..) anime"

` AddCategoryMapping(28,TorznabCatType.BooksEbook);`
to
`AddCategoryMapping(28, TorznabCatType.TVAnime);`

**Comment by JigSawFr** [comment]
@eyotiste your issue is now fixed by PR #296 
Issue of downloading torrent from PhxBit provider is now fixed by PR #293

**Comment by JigSawFr** [comment]
**Updating FADN Provider with:**
- Login Check (ISS. #286 #297 #292)
- New logo
- Optimized Provider

**Comment by fana13** [comment]
Hi @JigSawFr, have some problems in all frenches providers.
I've this error : 
4-05 18:06:27 INFO
[hpotato.core.plugins.base] Opening url: get http://xx.xx.xx.xx/jackett/potato/phxbit?imdbid=tt3850214&user=&passkey=xxx
04-05 18:06:27 ERROR
[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://xx.xx.xx.xx/jackett/potato/phxbit?imdbid=tt3850214&user=&passkey=xxx&user=&passkey=xxx
04-05 18:06:27 DEBUG
[hpotato.core.plugins.base] Failed getting cache: Traceback (most recent call last): HTTPError: 401 Client Error: Unauthorized for url: http://xx.xx.xx.xx/jackett/potato/phxbit?imdbid=tt3850214&user=&passkey=xxx

In this case is for PHX but it's the same thing for ABN or Bluetigers right now (i don't speak for F-ADN because is down now).
Have you an idea ?
In jackett search is good and also test too.
But in CP nothing works.
Thx ;)

**Comment by JigSawFr** [comment]
@fana13 Please create issue for each problems please.
It's strange, are you sure your APIKEY in CP for Jackett is right ?
Seems Jackett reject all your calls from CP and return unauthorized.

**Comment by itdaboyz** [comment]
PhxBit closed, you can remove it.
Sadly it didn't last long.

**Comment by JigSawFr** [comment]
Roadmap reopened for fixes :) Stay tuned.

**Comment by leloki** [comment]
Hi @JigSawFr !
T411 is back !!!!! 
https://t411.si

Could you add it in Jackett ?

**Comment by JigSawFr** [comment]
@leloki hi, it's already present, but in my mind this tracker is not safe to use, be prudent.

**Comment by leloki** [comment]
@JigSawFr Hi, yes I tried it in Jackett but it seems broken, no results whatsoever. Why do you say it is unsafe ? Hadopi or something else ?

**Comment by JigSawFr** [comment]
This tracker is not a "real" tracker. It's just a mirror of files indexed from public trackers such as ThePirateBay and others. If you found magnet link, it's not a private / semi-private tracker.

**Comment by pipopop** [comment]
Hi Jigsaw. Here is a list of private french tracker that can be added:
[https://www.spacetorrent.cloud/](https://www.spacetorrent.cloud/)
[http://lesaloonv2-0.net/](http://lesaloonv2-0.net/)
[http://www.limit-of-eden.com/wqreyt/](http://www.limit-of-eden.com/wqreyt/)
[http://neo-tk.com/](http://neo-tk.com/)
[https://lechaudron.net/](https://lechaudron.net/)
[https://casa-torrent.be/](https://casa-torrent.be/)
[https://team-hush.org/](https://team-hush.org/)
[https://lapausetorrents.me](https://lapausetorrents.me)
[http://t4ever.co/](http://t4ever.co/)
[https://www.zone-torrent.net](https://www.zone-torrent.net)
[http://bettyboop-tk.biz/](http://bettyboop-tk.biz/)
[http://genration-rosco-tk.net](http://genration-rosco-tk.net)

I already update issues in generals issues for spacetorrent.cloud and lesaloonv2-0.net

Do you prefere that I post information here ?
Do you prefere that I ask for a tracker 1 by 1 ?
I have invitation for many of them if you need.

Great thanks for your work.
Pipopop
