### ISSUE TITLE
【REQ】Request to add New tracker t4ever.co

### ISSUE THREAD

**Issue by Bbram1** [Jackett/Jackett#3495]
Hi ! and thnx for your great job :) 
i come to ask you  to add 3 tracker , i was look your anwser from the another REQ  but i don't know how do HTML/CSS . 
I have invite for all tracker if you need 
- [x] ~~casa-torrent.be~~ error name not resolved
- [x] ~~lesaloonv2-0.net~~ duplicate #1551
- [x] ~~t4ever.co~~ shutdown

**Comment by Bbram1** [comment]
@kaso17 can you help me with this ?

**Comment by kaso17** [comment]
I currently have no time to add new indexers.

**Comment by garfield69** [comment]
If you send an invite for t4ever.co to garfield69 at outlook.com I will try to create a cardigann definition.
However if the site turns out to require native c# indexer support then I will not be able to complete this task.

**Comment by pipopop** [comment]
Dead site:
"e site est fermé
Pour des questions de sécurités et pour protéger les membres, j'ai décidé de fermer le site
La base de données à été détruite
Il n'existe aucune copie

Le tracker vient d'être supprimer

Merci à vous tous"

Here : [http://t4ever.co/index.php](http://t4ever.co/index.php)
