### ISSUE TITLE
[REQ] Please add some new trackers.

### ISSUE THREAD

**Issue by Deputant** [Jackett/Jackett#4969]
- [x] https://toloka.to/ ~~Public~~ Semi-private Ukrainian forum req c# #4970 
- [x] https://avg.club/ Private [09229dcf294911e032f32009a61a3a6d81a30a8e]
- [x] ~~https://teamhd.org/ Private (I have **no** invites)~~ duplicate of #4397
- [x] https://tapochek.net/ Private (I have **no** invites) req c# #4971
- [ ] https://peers.fm/ Private  (I have invites)  [assigned to Garfield69, work in progress]
- [x] https://tracker.0day.kiev.ua/  Private (I have **no** invites) #4972

**Comment by garfield69** [comment]
in future please raise separate request for each tracker, as it makes it easier to track progress, especially since some don't have invites right now and so may be on the shelf for some time.

**Comment by garfield69** [comment]
If you send an invite to garfieldsixtynine @ gmail.com I will have a go building a cardigann indexer.
But if the site turns out to require a native c# indexer then I will not be able to complete the task.

**Comment by Deputant** [comment]
A confirmation email has been sent to the address you specified (garfieldsixtynine @ gmail.com). They need to read and respond to this email before they can use their account. If they don't do this, the new account will be deleted automatically after a few days.

**Comment by garfield69** [comment]
registration and login to peers.fm successful. Thank you.

**Comment by garfield69** [comment]
Try out peers.fm and avg on Jackett pre-release 0.11.145

**Comment by Deputant** [comment]
Thank you. Peers works, AVG no works returns empty search results (rss also)

**Comment by garfield69** [comment]
I have added language support for Russian and Ukrainian to AVG so try out Jackett pre-release 0.11.147

**Comment by garfield69** [comment]
avg.club returning 
![image](https://user-images.githubusercontent.com/6933240/55295607-92a48480-546b-11e9-8c24-5839cab1a1e6.png)

**Comment by garfield69** [comment]
avg.club back to normal.

**Comment by garfield69** [comment]
avg.club currently returning  ERR_CONNECTION_TIMED_OUT
broken, gone or new domain?

**Comment by garfield69** [comment]
looks like avg have had a crash. http://avg.club is now returning on admin setup page
![image](https://user-images.githubusercontent.com/6933240/65012324-06c7db80-d96b-11e9-968a-6c755d4106e7.png)

**Comment by garfield69** [comment]
avg back to returning ERR_CONNECTION_TIMED_OUT
if someone does not post a "its working for me" comment  before the end of this month then I will delete this indexer

**Comment by garfield69** [comment]
last post from their twitter a/c was Aug 22

**Comment by garfield69** [comment]
site closed. https://vk.com/catalyst_rg
